apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtitle
  labels:
    app: subtitle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtitle
  template:
    metadata:
      labels:
        app: subtitle
    spec:
      containers:
        - name: subtitle
          image: sinsung6722/toykiwi_subtitle:v1
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates

          livenessProbe:
            httpGet:
              path: '/sanityCheck'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            successThreshold: 1
            periodSeconds: 5
            failureThreshold: 3