server:
  port: 8080

spring:
  application:
    name: video

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde

      bindings:
        event-in:
          group: video
          destination: toykiwi
          contentType: application/json
        event-out:
          destination: toykiwi
          contentType: application/json

logging:
  level:
    root: WARN
    toykiwi.video.custom: DEBUG

---

spring:
  profiles: default
  cloud.stream.kafka.binder.brokers: localhost:9092

server.port: 8082

---

spring:
  profiles: docker
  cloud.stream.kafka.binder.brokers: my-kafka:9092
