server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: video
          uri: http://localhost:8082
          predicates:
            - Path=/api/video/**
          filters:
            - RewritePath=/api/video/(?<segment>.*), /${segment}

        - id: collectedData
          uri: http://localhost:8084
          predicates:
            - Path=/api/collectedData/**
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}

        - id: externalSystem
          uri: http://localhost:8085
          predicates:
            - Path=/api/externalSystem/**
          filters:
            - RewritePath=/api/externalSystem/(?<segment>.*), /${segment}

        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

logging:
  level:
    root: WARN

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: video
          uri: http://video:8080
          predicates:
            - Path=/videos/**, 
        - id: subtitle
          uri: http://subtitle:8080
          predicates:
            - Path=/subtitles/**, 
        - id: collectedData
          uri: http://collectedData:8080
          predicates:
            - Path=, 
        - id: externalSystem
          uri: http://externalSystem:8080
          predicates:
            - Path=, 
        - id: externalSystemProxy
          uri: http://externalSystemProxy:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080

logging:
  level:
    root: WARN