server:
  port: 8088

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

logging:
  level:
    root: WARN

---

spring:
  profiles: host

  cloud:
    gateway:
      routes:
        - id: video
          uri: http://localhost:8082
          predicates:
            - Path=/api/video/**
          filters:
            - RewritePath=/api/video/(?<segment>.*), /${segment}

        - id: collectedData
          uri: http://localhost:8084
          predicates:
            - Path=/api/collectedData/**
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}

        - id: externalSystem
          uri: http://localhost:8085
          predicates:
            - Path=/api/externalSystem/**
          filters:
            - RewritePath=/api/externalSystem/(?<segment>.*), /${segment}

        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**

---

spring:
  profiles: docker

  cloud:
    gateway:
      routes:
        - id: video
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/video/**
          filters:
            - RewritePath=/api/video/(?<segment>.*), /${segment}

        - id: collectedData
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/api/collectedData/**
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}

        - id: externalSystem
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/api/externalSystem/**
          filters:
            - RewritePath=/api/externalSystem/(?<segment>.*), /${segment}

        - id: frontend
          uri: http://host.docker.internal:3000
          predicates:
            - Path=/**

---

spring:
  profiles: kubernates

  cloud:
    gateway:
      routes:
        - id: video
          uri: http://video:8080
          predicates:
            - Path=/api/video/**
          filters:
            - RewritePath=/api/video/(?<segment>.*), /${segment}

        - id: collectedData
          uri: http://collected-data:8080
          predicates:
            - Path=/api/collectedData/**
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}

        - id: externalSystem
          uri: http://external-system:8085
          predicates:
            - Path=/api/externalSystem/**
          filters:
            - RewritePath=/api/externalSystem/(?<segment>.*), /${segment}

        - id: frontend
          uri: http://frontend:3000
          predicates:
            - Path=/**
