apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
  labels:
    app: video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
        - name: video
          image: sinsung6722/toykiwi_video:v1
          ports:
            - containerPort: 8080
          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates
          
          livenessProbe:
            httpGet:
              path: '/sanityCheck'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            successThreshold: 1
            periodSeconds: 5
            failureThreshold: 3