server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: video
          uri: http://localhost:8082
          predicates:
            - Path=/videos/**, 
        - id: subtitle
          uri: http://localhost:8083
          predicates:
            - Path=/subtitles/**, 
        - id: collectedData
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: External Systems
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: video
          uri: http://video:8080
          predicates:
            - Path=/videos/**, 
        - id: subtitle
          uri: http://subtitle:8080
          predicates:
            - Path=/subtitles/**, 
        - id: collectedData
          uri: http://collectedData:8080
          predicates:
            - Path=, 
        - id: External Systems
          uri: http://externalSystems:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
