apiVersion: v1
kind: Service
metadata:
  name: externalSystemProxy
  labels:
    app: externalSystemProxy
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: externalSystemProxy