apiVersion: v1
kind: Service
metadata:
  name: external-system-proxy
  labels:
    app: external-system-proxy
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: external-system-proxy