apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-system
  labels:
    app: external-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-system
  template:
    metadata:
      labels:
        app: external-system
    spec:
      containers:
        - name: external-system
          image: sinsung6722/toykiwi_external_system:v1
          ports:
            - containerPort: 8085
          env:
            - name: AWS_ACCESS_KEY
              value: AWS_ACCESS_KEY_VALUE
            - name: AWS_SECRET_ACCESS_KEY
              value: AWS_SECRET_ACCESS_KEY_VALUE
            - name: OPENAI_API_KEY
              value: OPENAI_API_KEY_VALUE
            - name: DEEPL_API_KEY
              value: DEEPL_API_KEY_VALUE
            - name: AWS_BUCKET_NAME
              value: sinsung6722-toywiki
            - name: AWS_REGION_CODE
              value: ap-northeast-2